global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # If your target is running on the host machine
  - job_name: 'your-application'
    static_configs:
      - targets: ['host.docker.internal:YOUR_TARGET_PORT']